// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wallet.Infrastructure;

#nullable disable

namespace Wallet.Infrastructure.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20260930075531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("numero_socio_seq");

            modelBuilder.Entity("Wallet.Tenant.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dni");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("document");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<long>("NumeroSocio")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_socio");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("socio_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<string>("VcId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vc_id");

                    b.HasKey("Id");

                    b.HasIndex("SocioId")
                        .HasDatabaseName("ix_credentials_socio_id");

                    b.HasIndex("ValidFrom")
                        .IsDescending()
                        .HasDatabaseName("ix_credentials_valid_from");

                    b.HasIndex("VcId")
                        .IsUnique()
                        .HasDatabaseName("ux_credentials_vc_id");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("Wallet.Tenant.Socio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dni");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<long>("NumeroSocio")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_socio");

                    b.Property<string>("SubjectDid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_did");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasDatabaseName("ux_socios_dni");

                    b.HasIndex("NumeroSocio")
                        .IsUnique()
                        .HasDatabaseName("ux_socios_numero_socio");

                    b.HasIndex("SubjectDid")
                        .IsUnique()
                        .HasDatabaseName("ux_socios_subject_did");

                    b.ToTable("socios", (string)null);
                });

            modelBuilder.Entity("Wallet.Tenant.Credential", b =>
                {
                    b.HasOne("Wallet.Tenant.Socio", null)
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
